import Loading from "@/components/Loading";
// import HomePage from "@/pages/homePage/HomePage";
import dynamic from "next/dynamic";

const DynamicHomePage = dynamic(() => import("@/pages/homePage/HomePage"), {
  loading: () => <Loading />,
})

export const metadata = {
  title: "CFAM",
  description: "Generated by create next app",  
}
export default function Home() {
  return <DynamicHomePage />;
}
