import HomePage from "@/pages/homePage/HomePage";

export const metadata = {
  title: "CFAM",
  description: "Generated by create next app",  
}
export default function Home() {
  return <HomePage />;
}
