export const mummyData = [
    {
        "id": "1",
        "title": " Luxury Apartment Luxury Apartment Luxury Apartment Luxury Apartment Luxury Apartment Luxury Apartment  ",
        "last_updated": "5 seconds ago",
        "location": "Downtown",
        "number_of_rooms": 3,
        "floor_area": "1500 sqft",
        "number_of_floors": 1,
        "number_of_bathrooms": 2,
        "price": "$2000",
        "discount": "$1000",
        "listing_type": "sale"
    },
    {
        "id": "2",
        "title": "Cozy Studio",
        "last_updated": "5 seconds ago",
        "location": "Suburb",
        "number_of_rooms": 1,
        "floor_area": "500 sqft",
        "number_of_floors": 1,
        "number_of_bathrooms": 1,
        "price": "$800",
        "listing_type": "rent"
    },
    {
        "id": "3",
        "title": "Spacious Penthouse",
        "last_updated": "5 seconds ago",
        "location": "City Center",
        "number_of_rooms": 5,
        "floor_area": "3000 sqft",
        "number_of_floors": 2,
        "number_of_bathrooms": 3,
        "price": "$5000",
        "listing_type": "sale"
    },
    {
        "id": "4",
        "title": "Modern Townhouse",
        "last_updated": "5 seconds ago",
        "location": "Residential Area",
        "number_of_rooms": 4,
        "floor_area": "2000 sqft",
        "number_of_floors": 3,
        "number_of_bathrooms": 2,
        "price": "$3500",
        "listing_type": "rent"
    },
    {
        "id": "5",
        "title": "Charming Cottage",
        "last_updated": "5 seconds ago",
        "location": "Countryside",
        "number_of_rooms": 2,
        "floor_area": "1000 sqft",
        "number_of_floors": 1,
        "number_of_bathrooms": 1,
        "price": "$1500",
        "listing_type": "sale"
    },
    {
        "id": "6",
        "title": "Beachfront Villa",
        "last_updated": "5 seconds ago",
        "location": "Coastal Area",
        "number_of_rooms": 6,
        "floor_area": "4000 sqft",
        "number_of_floors": 1,
        "number_of_bathrooms": 4,
        "price": "$7000",
        "listing_type": "rent"
    },
    {
        "id": "7",
        "title": "Rustic Cabin",
        "last_updated": "5 seconds ago",
        "location": "Mountain",
        "number_of_rooms": 3,
        "floor_area": "1200 sqft",
        "number_of_floors": 1,
        "number_of_bathrooms": 1,
        "price": "$1200",
        "listing_type": "sale"
    },
    {
        "id": "8",
        "title": "Urban Loft",
        "last_updated": "5 seconds ago",
        "location": "City Center",
        "number_of_rooms": 2,
        "floor_area": "800 sqft",
        "number_of_floors": 1,
        "number_of_bathrooms": 1,
        "price": "$1800",
        "listing_type": "rent"
    },
    {
        "id": "9",
        "title": "Elegant Mansion",
        "last_updated": "5 seconds ago",
        "location": "Exclusive Neighborhood",
        "number_of_rooms": 8,
        "floor_area": "6000 sqft",
        "number_of_floors": 3,
        "number_of_bathrooms": 6,
        "price": "$10000",
        "listing_type": "sale"
    },
    {
        "id": "10",
        "title": "Cosy Bungalow",
        "last_updated": "5 seconds ago",
        "location": "Suburb",
        "number_of_rooms": 4,
        "floor_area": "1800 sqft",
        "number_of_floors": 1,
        "number_of_bathrooms": 2,
        "price": "$2500",
        "listing_type": "rent"
    },
    {
        "id": "11",
        "title": "Traditional Farmhouse",
        "last_updated": "5 seconds ago",
        "location": "Rural Area",
        "number_of_rooms": 5,
        "floor_area": "2500 sqft",
        "number_of_floors": 2,
        "number_of_bathrooms": 3,
        "price": "$3000",
        "listing_type": "sale"
    },
    {
        "id": "12",
        "title": "Contemporary Condo",
        "last_updated": "5 seconds ago",
        "location": "Metropolitan",
        "number_of_rooms": 2,
        "floor_area": "1000 sqft",
        "number_of_floors": 1,
        "number_of_bathrooms": 2,
        "price": "$2200",
        "listing_type": "rent"
    },
    {
        "id": "13",
        "title": "Lakefront Retreat",
        "last_updated": "5 seconds ago",
        "location": "Lake",
        "number_of_rooms": 3,
        "floor_area": "1500 sqft",
        "number_of_floors": 1,
        "number_of_bathrooms": 2,
        "price": "$2800",
        "listing_type": "sale"
    },
    {
        "id": "14",
        "title": "Historic Mansion",
        "last_updated": "5 seconds ago",
        "location": "Heritage District",
        "number_of_rooms": 10,
        "floor_area": "8000 sqft",
        "number_of_floors": 3,
        "number_of_bathrooms": 6,
        "price": "$15000",
        "listing_type": "rent"
    },
    {
        "id": "15",
        "title": "Sleek Townhouse",
        "last_updated": "5 seconds ago",
        "location": "Urban",
        "number_of_rooms": 3,
        "floor_area": "1600 sqft",
        "number_of_floors": 2,
        "number_of_bathrooms": 2,
        "price": "$3200",
        "listing_type": "sale"
    },
    {
        "id": "16",
        "title": "Mountain Chalet",
        "last_updated": "5 seconds ago",
        "location": "Alpine Region",
        "number_of_rooms": 4,
        "floor_area": "2000 sqft",
        "number_of_floors": 1,
        "number_of_bathrooms": 2,
        "price": "$4000",
        "listing_type": "rent"
    }
]